mode: deployment
replicaCount: 1

image:
  repository: otel/opentelemetry-collector-contrib

presets:
  kubernetesAttributes:
    enabled: true

ports:
  prometheus:
    enabled: true
    containerPort: 8889
    servicePort: 8889
    protocol: TCP

serviceMonitor:
  enabled: true
  metricsEndpoints:
    - port: prometheus
  extraLabels:
    release: kube-prometheus-stack

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317

  exporters:
    otlp_grpc/tempo:
      endpoint: tempo.monitoring.svc:4317
      tls:
        insecure: true
    prometheus:
      endpoint: 0.0.0.0:8889
      resource_to_telemetry_conversion:
        enabled: true

  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [k8s_attributes, batch]
        exporters: [otlp_grpc/tempo]
      metrics:
        receivers: [otlp]
        processors: [k8s_attributes, batch]
        exporters: [prometheus]
      logs: null
